language: node_js
node_js:
  - "4.4.7"
cache:
  directories:
    - node_modules
before_script:
    - npm install -g gulp
script:
    - gulp unit-tests
    - gulp lint

# https://docs.travis-ci.com/user/notifications/#Slack-notifications
#https://github.com/dwyl/learn-travis
notifications:
  slack: free-knights:dCzjsrracXvYHh421QPB2bKe