
// ---------- FORUM actions ----------
export const GET_FORUM_CATEGORIES_SUCCESS = 'GET_FORUM_CATEGORIES_SUCCESS';

export const GET_FORUM_TOPIC_SUCCESS = 'GET_FORUM_TOPIC_SUCCESS';
export const POST_FORUM_TOPIC_SUCCESS = 'POST_FORUM_TOPIC_SUCCESS';