
// ---------- FORUM actions ----------
export const GET_FORUM_CATEGORIES_SUCCESS = 'GET_FORUM_CATEGORIES_SUCCESS';

export const GET_FORUM_TOPIC_SUCCESS = 'GET_FORUM_TOPIC_SUCCESS';
export const POST_FORUM_TOPIC_SUCCESS = 'POST_FORUM_TOPIC_SUCCESS';

/**
 * Gallery actions
 */
export const gallery_actions = {
  REQUEST_GALLERY_LIST:'REQUEST_GALLERY_LIST',
  RECEIVE_GALLERY_LIST: 'RECEIVE_GALLERY_LIST'
}
