// ---------- FORUM actions ----------

export const forum_actions = {
    GET_FORUM_LIST_SUCCESS: 'GET_FORUM_LIST_SUCCESS',
    GET_FORUM_SUCCESS: 'GET_FORUM_SUCCESS',
    POST_FORUM_SUCCESS: 'POST_FORUM_SUCCESS',
    GET_TOPIC_SUCCESS: 'GET_TOPIC_SUCCESS',
    POST_TOPIC_SUCCESS: 'POST_TOPIC_SUCCESS',
    GET_POST_SUCCESS: 'GET_POST_SUCCESS',
    POST_POST_SUCCESS: 'POST_POST_SUCCESS'
};


/**
 * Gallery actions
 */
export const gallery_actions = {
    REQUEST_GALLERY_LIST: 'REQUEST_GALLERY_LIST',
    RECEIVE_GALLERY_LIST: 'RECEIVE_GALLERY_LIST',
    REQUEST_GALLERY_COUNT: 'REQUEST_GALLERY_COUNT',
    RECEIVE_GALLERY_COUNT: 'RECEIVE_GALLERY_COUNT'
};


export const old_forum_actions = {
    GET_FORUM_CATEGORIES_SUCCESS: 'GET_FORUM_CATEGORIES_SUCCESS',
    GET_FORUM_TOPIC_SUCCESS: 'GET_FORUM_TOPIC_SUCCESS',
    POST_FORUM_TOPIC_SUCCESS: 'POST_FORUM_TOPIC_SUCCESS'
};


/**
 * Actions for Sign in and up
 */
export const sign_in_up_actions = {
    SIGN_UP: 'SIGN_UP',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILE: 'SIGN_UP_FAILE'
}